### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by sudhirgoswami** [kodlar/M101DotNet.WebApp#1]
I am facing problem.
## My records is like below 

 "_id" : ObjectId("55d866b355d6b803b8714110"),
 "Author" : "GdablrI",
 "Title" : "EHKfCCcaDc",
 "Content" : "TOPagFbzehmOMYEinapgw",
 "Tags" : [
         "kbH",
         "yGL",
         "sea"
 ],
 "Comments" : null,
##  "CreatedAtUtc" : ISODate("2015-08-22T12:10:27.335Z")

when I start the project its work fine but when click on the "View" button  comment its thrown an null exception in comment model.

then I noticed in all records doesn't exits comments.

So execute given below update command .
db.posts.update ( {} , {$set : {Comments : {"Author" : "Jack" , "Content" : "This is a comment" , CreatedAtUtc : Date.now()/1000  } } }, {multi :true }  )

Now when again restart the project its throwing error on 

HomeController.cs
 var recentPosts = await blogContext.Posts.Find(filter).Limit(10).Sort("{Date:1}").ToListAsync(); 

Its saying can not Deserialze a List<Comment> from Bson type 'Document'
![error](https://cloud.githubusercontent.com/assets/5566851/9427186/637a75cc-498c-11e5-90fb-a64664f7c37f.png)

**Comment by sudhirgoswami** [comment]
This is the first time screen when in Comment = null in records.
![error1](https://cloud.githubusercontent.com/assets/5566851/9427195/b35be544-498c-11e5-83f3-acf19ee384e4.png)

When I am clicking on View Button. Then It thowing 
![erro2](https://cloud.githubusercontent.com/assets/5566851/9427199/005bacb2-498d-11e5-8acb-7dbabe46f578.png)

**Comment by kodlar** [comment]
Hi sudhirgoswami, are you solve this problem? or already waiting my answer?

**Comment by sudhirgoswami** [comment]
Hi Kodlar ,
I fixed the issue.
Thanks

**Comment by kodlar** [comment]
sorry for delay and I was in holiday couldn't see your message
